// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8OdZv_x6KD7Y3lcsfvOJNyl82i6w286w',
    appId: '1:852324234431:web:05c00a8b9bda80ba3c020a',
    messagingSenderId: '852324234431',
    projectId: 'spendsmart-bc0f2',
    authDomain: 'spendsmart-bc0f2.firebaseapp.com',
    storageBucket: 'spendsmart-bc0f2.firebasestorage.app',
    measurementId: 'G-MR80LW3TWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4b6ed1YPLJCy0L2jKXExM224BO559JCo',
    appId: '1:852324234431:android:ab3e7883443a63ff3c020a',
    messagingSenderId: '852324234431',
    projectId: 'spendsmart-bc0f2',
    storageBucket: 'spendsmart-bc0f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjET5fQwG3cbelBtNz_DLjvDJv-vSzepI',
    appId: '1:852324234431:ios:4f7c6c6dbb6639e43c020a',
    messagingSenderId: '852324234431',
    projectId: 'spendsmart-bc0f2',
    storageBucket: 'spendsmart-bc0f2.firebasestorage.app',
    iosBundleId: 'com.example.spendsmart',
  );
}
